// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    _Cantainer: typeof import('./src/components/demo/pages/_Cantainer.vue')['default']
    _child: typeof import('./src/components/demo/vue/_child.vue')['default']
    _EnergyFlow: typeof import('./src/components/demo/pages/_EnergyFlow.vue')['default']
    _father: typeof import('./src/components/demo/vue/_father.vue')['default']
    AntVDemos: typeof import('./src/components/demo/pages/AntVDemos.vue')['default']
    BlogContent: typeof import('./src/components/blog/BlogContent.vue')['default']
    BlogPage: typeof import('./src/components/blog/BlogPage.vue')['default']
    BouncyBall: typeof import('./src/components/demo/cssanimation/BouncyBall.vue')['default']
    BubbleBall: typeof import('./src/components/demo/cssanimation/BubbleBall.vue')['default']
    ComponentMsg: typeof import('./src/components/demo/vue/ComponentMsg.vue')['default']
    DefaultDemoContent: typeof import('./src/components/demo/DefaultDemoContent.vue')['default']
    DemoComponents: typeof import('./src/components/demo/pages/DemoComponents.vue')['default']
    DemoPinia: typeof import('./src/components/demo/vue/DemoPinia.vue')['default']
    DemoPiniaA: typeof import('./src/components/demo/vue/components/DemoPiniaA.vue')['default']
    DemoPiniaB: typeof import('./src/components/demo/vue/components/DemoPiniaB.vue')['default']
    DemoRefVsReactive: typeof import('./src/components/demo/vue/DemoRefVsReactive.vue')['default']
    FanytasyVideo: typeof import('./src/components/demo/pages/FanytasyVideo.vue')['default']
    HomeBlog: typeof import('./src/components/blog/HomeBlog.vue')['default']
    HomeBlogCategory: typeof import('./src/components/blog/HomeBlogCategory.vue')['default']
    HomeBlogLeftSide: typeof import('./src/components/blog/HomeBlogLeftSide.vue')['default']
    HomeBlogNav: typeof import('./src/components/blog/HomeBlogNav.vue')['default']
    HomeDemoPage: typeof import('./src/components/demo/HomeDemoPage.vue')['default']
    HomePage: typeof import('./src/components/home/HomePage.vue')['default']
    Introduction: typeof import('./src/components/home/introduction.md')['default']
    IntroductionPanel: typeof import('./src/components/home/IntroductionPanel.vue')['default']
    NotFound: typeof import('./src/components/common/NotFound.vue')['default']
    PageFooter: typeof import('./src/components/common/PageFooter.vue')['default']
    PageHeader: typeof import('./src/components/common/PageHeader.vue')['default']
    PagePreview: typeof import('./src/components/demo/pages/components/PagePreview.vue')['default']
    README: typeof import('./src/components/demo/README.md')['default']
    RightAsideNavBar: typeof import('./src/components/nav/RightAsideNavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TestDemo2: typeof import('./src/components/demo/cssanimation/TestDemo2.vue')['default']
    WeatherHeader: typeof import('./src/components/common/WeatherHeader.vue')['default']
  }
}
