// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BlogContent: typeof import('./src/components/blog/BlogContent.vue')['default']
    HomeBlogCategory: typeof import('./src/components/blog/HomeBlogCategory.vue')['default']
    HomeBlogLeftSide: typeof import('./src/components/blog/HomeBlogLeftSide.vue')['default']
    HomeBlogNav: typeof import('./src/components/blog/HomeBlogNav.vue')['default']
    IntroductionPanel: typeof import('./src/components/home/IntroductionPanel.vue')['default']
    PageFooter: typeof import('./src/components/common/PageFooter.vue')['default']
    PageHeader: typeof import('./src/components/common/PageHeader.vue')['default']
    RightAsideNavBar: typeof import('./src/components/demo/RightAsideNavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WeatherHeader: typeof import('./src/components/common/WeatherHeader.vue')['default']
  }
}
